### PR TITLE
Fix namespace of inject-style! in macro

### PR DESCRIPTION
**Pull request by bnoguchi**

### CODE REVIEW

**Comment by mt-bt** [comment]
Thanks 👍 !

**Comment by bnoguchi** [comment]
Can you let me know when you publish the new version to clojars?

**Comment by mt-bt** [comment]
done 💯 !

**Comment by bnoguchi** [comment]
Thanks. Did you publish as 0.1.1-SNAPSHOT or 0.1.1.?

**Comment by mt-bt** [comment]
no worries! as 0.1.1-SNAPSHOT for now!

**Comment by mt-bt** [comment]
published as 0.1.1 now.

**Pull request merged**
